apiVersion: 1

datasources:
  - name: Dobley Elasticsearch
    uid: dobley-elasticsearch
    type: elasticsearch
    access: proxy
    url: http://dobley.elasticsearch:9200
    database: dobley-logs*
    isDefault: true
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.0.0"
      logMessageField: Body
      logLevelField: SeverityText
