<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.16" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.11" />
      <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Dobley.Data.Core\Dobley.Data.Core.csproj" />
    </ItemGroup>

</Project>
