{
 "title": "Dobley Observability",
 "tags": [
  "dobley",
  "logs",
  "elasticsearch"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "serviceName",
    "label": "Service",
    "query": "*,Gateway : \"Dobley.Endpoints.Gateway\",API : \"Dobley.Endpoints.Api\",Auth : \"Dobley.Endpoints.Auth\""
   },
   { "name": "logSearch", "label": "Search", "query": "Body:*" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Logs",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Resource.service.name.keyword:${serviceName:raw} AND NOT Attributes.Path:\"/health\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Warnings",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Resource.service.name.keyword:${serviceName:raw} AND SeverityText:Warning AND NOT Attributes.Path:\"/health\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Errors / 5xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Resource.service.name.keyword:${serviceName:raw} AND (SeverityText:Error OR Attributes.StatusCode:[500 TO 599]) AND NOT Attributes.Path:\"/health\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Bad Requests",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Resource.service.name.keyword:${serviceName:raw} AND Attributes.StatusCode:[400 TO 499] AND NOT Attributes.Path:\"/health\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Rate By Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "{{term Resource.service.name.keyword}}",
     "bucketAggs": [
      {
       "field": "Resource.service.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Resource.service.name.keyword:${serviceName:raw} AND NOT Attributes.Path:\"/health\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HTTP Statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "{{term Attributes.StatusCode}}",
     "bucketAggs": [
      {
       "field": "Attributes.StatusCode",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "Resource.service.name.keyword:${serviceName:raw} AND Attributes.StatusCode:* AND NOT Attributes.Path:\"/health\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Recent Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "Resource.service.name.keyword:${serviceName:raw} AND (${logSearch:raw}) AND NOT Attributes.Path:\"/health\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Warnings, Errors, 4xx, 5xx",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "Resource.service.name.keyword:${serviceName:raw} AND (SeverityText:Warning OR SeverityText:Error OR Attributes.StatusCode:[400 TO 599]) AND NOT Attributes.Path:\"/health\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Raw Documents",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "type": "raw_document" }
     ],
     "query": "Resource.service.name.keyword:${serviceName:raw} AND Attributes.Path:* AND NOT Attributes.Path:\"/health\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}